theme: jekyll-theme-minimal
title: Ahana Pradhan
description: Assistant Professor, CSE, 
<a href="https://www.iiitb.ac.in/" target="_blank"  rel="noopener noreferrer">International Institute of Information Technology Bangalore</a>
